# Version catalog updates generated at 2025-03-09T14:44:25.345212
#
# Contents of this file will be applied to libs.versions.toml when running versionCatalogApplyUpdates.
#
# Comments will not be applied to the version catalog when updating.
# To prevent a version upgrade, comment out the entry or remove it.
#
[libraries]
# From version 2.2.0 --> 2.2.1
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
# From version 1.15.0 --> 1.16.0-alpha02
androidx-core-ktx = "androidx.core:core-ktx:1.16.0-alpha02"
# From version 2.1.0 --> 2.2.0
androidx-core-testing = "androidx.arch.core:core-testing:2.2.0"
# From version 3.6.1 --> 3.7.0-alpha01
androidx-espresso-core = "androidx.test.espresso:espresso-core:3.7.0-alpha01"
# From version 1.2.1 --> 1.3.0-alpha01
androidx-junit = "androidx.test.ext:junit:1.3.0-alpha01"
# From version 2.8.7 --> 2.9.0-alpha07
androidx-navigation-fragment-ktx = "androidx.navigation:navigation-fragment-ktx:2.9.0-alpha07"
# From version 2.8.7 --> 2.9.0-alpha07
androidx-navigation-ui-ktx = "androidx.navigation:navigation-ui-ktx:2.9.0-alpha07"
# From version 2.6.1 --> 2.7.0-rc01
androidx-room-compiler = "androidx.room:room-compiler:2.7.0-rc01"
# From version 2.6.1 --> 2.7.0-rc01
androidx-room-ktx = "androidx.room:room-ktx:2.7.0-rc01"
# From version 2.6.1 --> 2.7.0-rc01
androidx-room-runtime = "androidx.room:room-runtime:2.7.0-rc01"
# From version 2.6.1 --> 2.7.0-rc01
androidx-room-testing = "androidx.room:room-testing:2.7.0-rc01"
# From version 2.53 --> 2.55
hilt-android = "com.google.dagger:hilt-android:2.55"
# From version 2.53 --> 2.55
hilt-compiler = "com.google.dagger:hilt-compiler:2.55"
# From version 2.53 --> 2.55
hilt-testing = "com.google.dagger:hilt-android-testing:2.55"
# From version 1.3.9 --> 1.10.1
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.1"
# From version 1.3.8 --> 1.10.1
kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.1"
# From version 4.8.0 --> 5.0.0-alpha.14
logging-interceptor = "com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.14"
# From version 6.1.0 --> 6.6.3
lottie = "com.airbnb.android:lottie:6.6.3"
# From version 1.12.0 --> 1.13.0-alpha11
material = "com.google.android.material:material:1.13.0-alpha11"
# From version 1.0.1 --> 1.4.4
truth = "com.google.truth:truth:1.4.4"

[plugins]
# From version 8.7.2 --> 8.10.0-alpha08
android-application = "com.android.application:8.10.0-alpha08"
# From version 1.23.7 --> 1.23.8
detekt = "io.gitlab.arturbosch.detekt:1.23.8"
# From version 0.41.0 --> 0.52.0
gradle-versions = "com.github.ben-manes.versions:0.52.0"
# From version 2.53 --> 2.55
hilt-plugin = "com.google.dagger.hilt.android:2.55"
# From version 1.9.24 --> 2.1.20-RC2
kotlin-android = "org.jetbrains.kotlin.android:2.1.20-RC2"
# From version 1.9.24 --> 2.1.20-RC2
kotlin-kapt = "org.jetbrains.kotlin.kapt:2.1.20-RC2"
# From version 1.9.25-1.0.20 --> 2.1.20-RC2-1.0.31
ksp = "com.google.devtools.ksp:2.1.20-RC2-1.0.31"
# From version 12.1.2 --> 12.2.0
ktlint = "org.jlleitschuh.gradle.ktlint:12.2.0"
