name: Android Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: |
          echo "$FIREBASE_SECRET" | base64 -d > app/google-services.json
          cat app/google-services.json

      # https://medium.com/@thiagolopessilva/running-android-unit-testing-on-github-action-with-a-project-that-contains-firebase-dependency-621603363bc1
      - name: Decode local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo -e "${LOCAL_PROPERTIES}" > local.properties
          cat local.properties

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties','gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Test
        run: ./gradlew clean build --stacktrace

      - name: Lint Check
        run: ./gradlew ktlintCheck

      - name: Run Detekt
        run: ./gradlew detekt